apiVersion: v1
kind: Service
metadata:
  name: orbitile-power-backend-server-cluster-ip
spec:
  type: ClusterIP
  selector:
    component: orbitile-power-backend
  ports:
   - port: 8080
     targetPort: 8080
