runtime: java11
instance_class: F4_1G
automatic_scaling:
  min_instances: 1
  max_instances: 5
  min_pending_latency: 500ms
  max_pending_latency: automatic
  max_concurrent_requests: 50

inbound_services:
  - warmup
